services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    environment:
      - TZ=Etc/UTC
    volumes:
      - $WORKSPACE_DIRECTORY/data/open-webui/data:/app/backend/data
    ports:
      - 9090:8080
    extra_hosts:
      - host.docker.internal:host-gateway

  open-webui-pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: open-webui-pipelines
    restart: unless-stopped
    volumes:
      - $WORKSPACE_DIRECTORY/data/open-webui/pipelines:/app/pipelines
    ports:
      - 9099:9099
    extra_hosts:
      - host.docker.internal:host-gateway
